name: Docker Build Main

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-20.04
    cancelable: true
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: zaks/vml:base